// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDuiW90UJFjiuCcJL4h1fm87JZRGFEzdo',
    appId: '1:991027730405:web:18e89619c47c16cf21410c',
    messagingSenderId: '991027730405',
    projectId: 'mynotes-prova-flutter',
    authDomain: 'mynotes-prova-flutter.firebaseapp.com',
    storageBucket: 'mynotes-prova-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD70vIbK07vQrNmuZQ992Orx8ArFc0xeog',
    appId: '1:991027730405:android:df22c251b923075421410c',
    messagingSenderId: '991027730405',
    projectId: 'mynotes-prova-flutter',
    storageBucket: 'mynotes-prova-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoj2-PvHrAURnobmMVcG8QDo7O6f_96xM',
    appId: '1:991027730405:ios:e713cbcd1b9fd5f121410c',
    messagingSenderId: '991027730405',
    projectId: 'mynotes-prova-flutter',
    storageBucket: 'mynotes-prova-flutter.appspot.com',
    iosClientId: '991027730405-q7mofetkiunhahol0dm2n619ja9jl85k.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoj2-PvHrAURnobmMVcG8QDo7O6f_96xM',
    appId: '1:991027730405:ios:e713cbcd1b9fd5f121410c',
    messagingSenderId: '991027730405',
    projectId: 'mynotes-prova-flutter',
    storageBucket: 'mynotes-prova-flutter.appspot.com',
    iosClientId: '991027730405-q7mofetkiunhahol0dm2n619ja9jl85k.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );
}
